name: Pull Image from Docker registry and Deploy to Kubernetes in aws ec2 instance
on:
  workflow_dispatch:
    branches:
      - main  
jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name <your-cluster-name> --region us-east-1

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes.yml